require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailboxesController do

  # This should return the minimal set of attributes required to create a valid
  # Mailbox. As you add validations to Mailbox, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mailboxes as @mailboxes" do
      mailbox = Mailbox.create! valid_attributes
      get :index
      assigns(:mailboxes).should eq([mailbox])
    end
  end

  describe "GET show" do
    it "assigns the requested mailbox as @mailbox" do
      mailbox = Mailbox.create! valid_attributes
      get :show, :id => mailbox.id.to_s
      assigns(:mailbox).should eq(mailbox)
    end
  end

  describe "GET new" do
    it "assigns a new mailbox as @mailbox" do
      get :new
      assigns(:mailbox).should be_a_new(Mailbox)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailbox as @mailbox" do
      mailbox = Mailbox.create! valid_attributes
      get :edit, :id => mailbox.id.to_s
      assigns(:mailbox).should eq(mailbox)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mailbox" do
        expect {
          post :create, :mailbox => valid_attributes
        }.to change(Mailbox, :count).by(1)
      end

      it "assigns a newly created mailbox as @mailbox" do
        post :create, :mailbox => valid_attributes
        assigns(:mailbox).should be_a(Mailbox)
        assigns(:mailbox).should be_persisted
      end

      it "redirects to the created mailbox" do
        post :create, :mailbox => valid_attributes
        response.should redirect_to(Mailbox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailbox as @mailbox" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailbox.any_instance.stub(:save).and_return(false)
        post :create, :mailbox => {}
        assigns(:mailbox).should be_a_new(Mailbox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailbox.any_instance.stub(:save).and_return(false)
        post :create, :mailbox => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailbox" do
        mailbox = Mailbox.create! valid_attributes
        # Assuming there are no other mailboxes in the database, this
        # specifies that the Mailbox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mailbox.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mailbox.id, :mailbox => {'these' => 'params'}
      end

      it "assigns the requested mailbox as @mailbox" do
        mailbox = Mailbox.create! valid_attributes
        put :update, :id => mailbox.id, :mailbox => valid_attributes
        assigns(:mailbox).should eq(mailbox)
      end

      it "redirects to the mailbox" do
        mailbox = Mailbox.create! valid_attributes
        put :update, :id => mailbox.id, :mailbox => valid_attributes
        response.should redirect_to(mailbox)
      end
    end

    describe "with invalid params" do
      it "assigns the mailbox as @mailbox" do
        mailbox = Mailbox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailbox.any_instance.stub(:save).and_return(false)
        put :update, :id => mailbox.id.to_s, :mailbox => {}
        assigns(:mailbox).should eq(mailbox)
      end

      it "re-renders the 'edit' template" do
        mailbox = Mailbox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailbox.any_instance.stub(:save).and_return(false)
        put :update, :id => mailbox.id.to_s, :mailbox => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailbox" do
      mailbox = Mailbox.create! valid_attributes
      expect {
        delete :destroy, :id => mailbox.id.to_s
      }.to change(Mailbox, :count).by(-1)
    end

    it "redirects to the mailboxes list" do
      mailbox = Mailbox.create! valid_attributes
      delete :destroy, :id => mailbox.id.to_s
      response.should redirect_to(mailboxes_url)
    end
  end

end
